server:
  port: 8761

eureka:
  instance:
    hostname:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://hostname:8761/eureka/
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85
    response-cache-update-interval-ms: 30000
    eviction-interval-timer-in-ms: 60000

logging:
  file:
    name: /var/log/eureka/eureka-server.log  # 로그 파일 위치
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 30